version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://localhost:5000
    restart: unless-stopped
    depends_on:
      - server 